### ISSUE TITLE
Kontribusi

### ISSUE THREAD

**Issue by aswansyahputra** [dasaptaerwin/thermostats#1]
Halo Pak Dasapta,

Dari deskripsinya proyek ini menarik dan bermanfaat. Apa boleh jika saya izin bergabung untuk berkontribusi? Kebetulan saya juga sedang mengembangkan aplikasi Shiny.

Salam,
Aswan

**Comment by dasaptaerwin** [comment]
Hi Mas Aswan
Salam kenaaaal. Tks sudah kontak saya. Maaf baru lihat ini. Kebetulan saya juga sedang perlu bantuan. Begini, proyek ini data dan ide dari saya, untuk developer Shiny nya sendiri Prana Ugi dosen USU (bisa digoogle, dia pengembang aplikasi Shiny StatCal). Dia sedang perlu bantuan waktu untuk menghosting source code Shinynya. Apakah Mas Aswan berkenan membantu. Kalau iya nanti saya kirim source code Shinynya via google drive dan masukkan namanya ke proyek ini :).

Bisakah sedikit cerita backgroundnya? :)

Email saya: dasaptaerwin3@gmail.com.
No WA: 08 2121 4242 10.

**Comment by aswansyahputra** [comment]
Salam kenal kembali Pak. Baik Pak, kebetulan saya pernah lihat aplikasi StatCal  buatan Pak Prana Ugi dan tim tersebut meskipun belum mencobanya secara penuh. Saya bersedia untuk berkontribusi Pak, insya Allah saya bisa bantu hosting di shinyapps.io maupun di VPS jika diperlukan.

Sedikit mengenai background saya, saat ini saya masih berstatus mahasiswa magister di Wageningen University and Research dengan program studi Food Technology dan spesialisasi Sensory Science. Aplikasi shiny yg sedang saya kembangkan namanya SenseHub, bisa diakses di aswansyahputra.shinyapps.io/SenseHub (masih versi alpha). SenseHub dikembangkan untuk digunakan dalam bidang ilmu sensoris pangan, meliputi rancangan penelitian hingga analisa data sensoris.

**Comment by dasaptaerwin** [comment]
Mas Aswan tks atas resumenya. Apakah sudah menerima undangan untuk mengakses data shiny app saya dan Ugi?

**Comment by aswansyahputra** [comment]
Sama-sama Pak. Belum ada undangannya Pak, alamat surel saya muhammadaswansyahputra@gmail.com

**Comment by dasaptaerwin** [comment]
Terima kasih Mas.

**Comment by dasaptaerwin** [comment]
Baru saja saya share google drive foldernya. Berisi data dan kode awal Shiny yg ditulis oleh Prana Ugi. Tks mas.

**Comment by aswansyahputra** [comment]
Selamat pagi (waktu Belanda) Pak Erwin,
Baik, undangan GDrive nya sudah saya terima. Saya sudah cek dan jalankan aplikasinya Pak, bagus!
Namun saya menemukan beberapa _issues_ yang bisa diperbaiki dan beberapa _improvements_ yang bisa dilakukan dari aspek _Shiny programming_ maupun _UI_. Insya Allah nanti saya ajukan _pull request_ ya Pak.

Salam.
